# Generated by Django 4.2.9 on 2024-01-17 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emp_app", "0002_alter_department_id_alter_employee_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="id",
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
